### PR TITLE
overhaul most of nix-bundle

### PR DESCRIPTION
**Pull request by cleverca22**
pulled nix-user-chroot into the same repo
put the startup command into a bash script, so the tarball job knows its deps
changed nix-user-chroot into a c++ program
added CLI flags to allow configuring the sandbox it produces

with these changes, you can now configure it to do things like mapping the host /etc to /host-etc inside the namespace, and have finer control over how pure the env variables are

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @matthewbauer

**Comment by dtzWill** [comment]
`release.nix` may need some touchups to pull in nix-user-chroot?

```console
$ nix build -f release.nix
$ ./result/bin/nix-bundle bash /bin/bash
error: getting attributes of path ‘/nix/store/xq6cia08kfg4y37b6wnjy3bid660swm0-nix-bundle-0.2.0/share/nix-bundle/nix-user-chroot’: No such file or directory
$ ls ./result/share/nix-bundle
AppRun.c  appdir.nix  appdir.sh  appimage-top.nix  appimage.nix  appimagetool.nix  default.nix  nix-bundle.sh  nix-run.sh  nix2appimage.sh
```

**Comment by matthewbauer** [comment]
Looks good! I can bump the version after this too.

**Comment by matthewbauer** [comment]
Thanks!

Error in https://github.com/matthewbauer/nix-bundle/pull/26#issuecomment-368525280 has also been fixed.

**Comment by dtzWill** [comment]
Oh, it was fixed separately in dcbfa1a76189710503a664bcaf9aea206ae78beb :).

**Pull request merged**
